export { default as activity } from './activity'
export { default as activities } from './activity' 
export { default as auth } from './auth' 
export { default as upload } from './upload' 
export { default as gpx } from './gpx' 